import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";

const exportPDF = (expenses) => {
  const doc = new jsPDF();

  // calculations
  const currentDate = new Date().toLocaleDateString();

  const total = expenses.reduce(
    (acc, expense) => acc + Number(expense.amount),
    0,
  );

  // colors
  const headerColor = [15, 23, 42];

  const accentColor = [14, 165, 233];

  // header
  doc.setFillColor(...headerColor);

  doc.rect(0, 0, 210, 38, "F");

  doc.setTextColor(255);

  doc.setFontSize(26);

  doc.text("Expense Report", 14, 22);

  doc.setFontSize(12);

  doc.text("All Transactions Overview", 14, 31);

  // date
  doc.setFontSize(11);

  doc.setTextColor(110);

  doc.text(`Generated on ${currentDate}`, 14, 50);

  // analytics cards
  const cards = [
    {
      title: "TOTAL EXPENSES",
      value: expenses.length,
    },

    {
      title: "TOTAL AMOUNT",
      value: `Rs. ${total.toLocaleString()}`,
    },
  ];

  let x = 14;

  cards.forEach((card) => {
    doc.setFillColor(248, 250, 252);

    doc.roundedRect(x, 60, 58, 26, 4, 4, "F");

    doc.setFontSize(9);

    doc.setTextColor(120);

    doc.text(card.title, x + 4, 70);

    doc.setFontSize(15);

    doc.setTextColor(20);

    doc.text(String(card.value), x + 4, 81);

    x += 66;
  });

  // expenses table
  autoTable(doc, {
    startY: 102,

    head: [["Expense", "Amount", "Date"]],

    body: expenses.map((expense) => [
      expense.name,

      `Rs. ${Number(expense.amount).toLocaleString()}`,

      new Date(expense.createdAt).toLocaleDateString(),
    ]),

    styles: {
      fontSize: 11,

      cellPadding: 6,

      halign: "center",

      valign: "middle",
    },

    headStyles: {
      fillColor: accentColor,

      textColor: 255,

      fontStyle: "bold",

      fontSize: 12,
    },

    bodyStyles: {
      textColor: 40,
    },

    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },

    margin: {
      left: 14,
      right: 14,
    },
  });

  // footer
  doc.setDrawColor(230, 230, 230);

  doc.line(14, 280, 196, 280);

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text("Generated by Expense Manager", 14, 287);

  doc.text("Personal Finance Report", 145, 287);

  // save
  doc.save(`expense-report-${Date.now()}.pdf`);
};

export default exportPDF;
