import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";

const exportBudgetPDF = (budget, expenses) => {
  const doc = new jsPDF();

  // calculations
  const totalSpent = expenses.reduce(
    (acc, expense) => acc + Number(expense.amount),
    0,
  );

  const remaining = Number(budget.amount) - totalSpent;

  const currentDate = new Date().toLocaleDateString();

  const budgetHealth = remaining < 0 ? "OVERSPENT" : "HEALTHY";

  // colors
  const headerColor = [15, 23, 42];

  const accentColor = [14, 165, 233];

  // header
  doc.setFillColor(...headerColor);

  doc.rect(0, 0, 210, 42, "F");

  doc.setTextColor(255);

  doc.setFontSize(28);

  doc.text(budget.name, 14, 22);

  doc.setFontSize(13);

  doc.text("Budget Expense Report", 14, 32);

  // date
  doc.setTextColor(120);

  doc.setFontSize(11);

  doc.text(`Generated on ${currentDate}`, 14, 52);

  // analytics cards
  const cards = [
    {
      title: "TOTAL BUDGET",
      value: `Rs. ${Number(budget.amount).toLocaleString()}`,
    },

    {
      title: "TOTAL SPENT",
      value: `Rs. ${totalSpent.toLocaleString()}`,
    },

    {
      title: "REMAINING",
      value: `Rs. ${remaining.toLocaleString()}`,
    },

    {
      title: "TRANSACTIONS",
      value: expenses.length,
    },
  ];

  let x = 14;

  cards.forEach((card) => {
    doc.setFillColor(248, 250, 252);

    doc.roundedRect(x, 64, 42, 28, 4, 4, "F");

    doc.setFontSize(9);

    doc.setTextColor(120);

    doc.text(card.title, x + 4, 74);

    doc.setFontSize(14);

    doc.setTextColor(20);

    doc.text(String(card.value), x + 4, 86);

    x += 47;
  });

  // budget health
  doc.setFillColor(
    budgetHealth === "HEALTHY" ? 34 : 239,
    budgetHealth === "HEALTHY" ? 197 : 68,
    budgetHealth === "HEALTHY" ? 94 : 68,
  );

  doc.roundedRect(14, 104, 182, 16, 3, 3, "F");

  doc.setTextColor(255);

  doc.setFontSize(12);

  doc.text(`Budget Health: ${budgetHealth}`, 20, 114);

  // expenses table
  autoTable(doc, {
    startY: 132,

    head: [["Expense", "Amount", "Date"]],

    body: expenses.map((expense) => [
      expense.name,

      `Rs. ${Number(expense.amount).toLocaleString()}`,

      new Date(expense.createdAt).toLocaleDateString(),
    ]),

    styles: {
      fontSize: 11,

      cellPadding: 6,

      halign: "center",

      valign: "middle",
    },

    headStyles: {
      fillColor: accentColor,

      textColor: 255,

      fontStyle: "bold",

      fontSize: 12,
    },

    bodyStyles: {
      textColor: 40,
    },

    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },

    margin: {
      left: 14,
      right: 14,
    },
  });

  // footer
  doc.setDrawColor(230, 230, 230);

  doc.line(14, 280, 196, 280);

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text("Generated by Expense Manager", 14, 287);

  doc.text("Personal Finance Report", 145, 287);

  // save
  doc.save(`${budget.name}-report.pdf`);
};

export default exportBudgetPDF;
